version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: altrack-db
    environment:
      POSTGRES_DB: food_tracker
      POSTGRES_USER: tracker
      POSTGRES_PASSWORD: tracker123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tracker -d food_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: altrack-backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://tracker:tracker123@postgres:5432/food_tracker
      PORT: 3001
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: altrack-frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://192.168.30.96:3001
      WATCHPACK_POLLING: true
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
